"""empty message

Revision ID: 29033ccaea2f
Revises: 34b6e3c4c3e2
Create Date: 2019-12-01 13:18:19.957425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29033ccaea2f'
down_revision = '34b6e3c4c3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zhutie',
    sa.Column('zhutieid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zhutietitle', sa.String(length=200), nullable=False),
    sa.Column('zhutievalue', sa.String(length=500), nullable=False),
    sa.Column('zhutielimit', sa.Integer(), nullable=False),
    sa.Column('zhutieup', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('blockid', sa.Integer(), nullable=True),
    sa.Column('zhutieTime', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['blockid'], ['block.blockid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('zhutieid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zhutie')
    # ### end Alembic commands ###
