"""empty message

Revision ID: 2f71ea69cbc3
Revises: 5fb508a7d618
Create Date: 2019-12-06 15:15:18.182974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f71ea69cbc3'
down_revision = '5fb508a7d618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('urlfor1', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block', 'urlfor1')
    # ### end Alembic commands ###
