"""empty message

Revision ID: 34b6e3c4c3e2
Revises: 5c4197e70452
Create Date: 2019-12-01 13:17:21.975263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b6e3c4c3e2'
down_revision = '5c4197e70452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('blockid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blockname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('blockid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block')
    # ### end Alembic commands ###
