"""empty message

Revision ID: 3e17c6f2936d
Revises: 65a822fa5fce
Create Date: 2019-12-01 16:06:38.491295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e17c6f2936d'
down_revision = '65a822fa5fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinglun', sa.Column('pingluntime', sa.DATE(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pinglun', 'pingluntime')
    # ### end Alembic commands ###
