"""empty message

Revision ID: 5fb508a7d618
Revises: e76e451ea80b
Create Date: 2019-12-03 17:35:31.151345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb508a7d618'
down_revision = 'e76e451ea80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('urlfor', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block', 'urlfor')
    # ### end Alembic commands ###
