"""empty message

Revision ID: 65a822fa5fce
Revises: c6b1cb1077ab
Create Date: 2019-12-01 16:06:15.443912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a822fa5fce'
down_revision = 'c6b1cb1077ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pinglun', 'pingluntime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinglun', sa.Column('pingluntime', sa.DATE(), nullable=False))
    # ### end Alembic commands ###
