"""empty message

Revision ID: 72fc284c59ec
Revises: 2f71ea69cbc3
Create Date: 2019-12-06 17:12:31.163660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fc284c59ec'
down_revision = '2f71ea69cbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pinglun_ibfk_1', 'pinglun', type_='foreignkey')
    op.drop_constraint('pinglun_ibfk_2', 'pinglun', type_='foreignkey')
    op.create_foreign_key(None, 'pinglun', 'user', ['userid'], ['userid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pinglun', 'zhutie', ['zhutieid'], ['zhutieid'], ondelete='CASCADE')
    op.drop_constraint('zhutie_ibfk_2', 'zhutie', type_='foreignkey')
    op.drop_constraint('zhutie_ibfk_1', 'zhutie', type_='foreignkey')
    op.create_foreign_key(None, 'zhutie', 'user', ['userid'], ['userid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'zhutie', 'block', ['blockid'], ['blockid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zhutie', type_='foreignkey')
    op.drop_constraint(None, 'zhutie', type_='foreignkey')
    op.create_foreign_key('zhutie_ibfk_1', 'zhutie', 'block', ['blockid'], ['blockid'])
    op.create_foreign_key('zhutie_ibfk_2', 'zhutie', 'user', ['userid'], ['userid'])
    op.drop_constraint(None, 'pinglun', type_='foreignkey')
    op.drop_constraint(None, 'pinglun', type_='foreignkey')
    op.create_foreign_key('pinglun_ibfk_2', 'pinglun', 'zhutie', ['zhutieid'], ['zhutieid'])
    op.create_foreign_key('pinglun_ibfk_1', 'pinglun', 'user', ['userid'], ['userid'])
    # ### end Alembic commands ###
