"""empty message

Revision ID: 8201903f7699
Revises: 29033ccaea2f
Create Date: 2019-12-01 14:08:57.266697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8201903f7699'
down_revision = '29033ccaea2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinglun',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pinglunup', sa.Integer(), nullable=False),
    sa.Column('pinglundown', sa.Integer(), nullable=False),
    sa.Column('zhutieid', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.ForeignKeyConstraint(['zhutieid'], ['zhutie.zhutieid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinglun')
    # ### end Alembic commands ###
