"""empty message

Revision ID: 9cf007d31c6c
Revises: 72fc284c59ec
Create Date: 2019-12-10 14:01:28.296209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf007d31c6c'
down_revision = '72fc284c59ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('touxiang', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'touxiang')
    # ### end Alembic commands ###
