"""empty message

Revision ID: c6b1cb1077ab
Revises: 8201903f7699
Create Date: 2019-12-01 16:05:15.267383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b1cb1077ab'
down_revision = '8201903f7699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinglun', sa.Column('pingluntime', sa.DATE(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pinglun', 'pingluntime')
    # ### end Alembic commands ###
