"""empty message

Revision ID: e76e451ea80b
Revises: 3e17c6f2936d
Create Date: 2019-12-03 15:44:35.854760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76e451ea80b'
down_revision = '3e17c6f2936d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('plscount', sa.Integer(), nullable=False))
    op.add_column('block', sa.Column('tzscount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block', 'tzscount')
    op.drop_column('block', 'plscount')
    # ### end Alembic commands ###
